### ISSUE TITLE
Falils to run due to max workers issue / 

### ISSUE THREAD

**Issue by 007-JB** [fafhrd91/aiohttp#6887] opened 2022-08-20 09:08 UTC
### Describe the bug

I get this:
```python-traceback
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Traceback (most recent call last):
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-8585f5fe9a5f>", line 16, in <module>
    loop.run_until_complete(main())
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "<ipython-input-6-8585f5fe9a5f>", line 7, in main
    async with session.get('http://python.org') as response:
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 809, in run_in_executor
    executor = concurrent.futures.ThreadPoolExecutor(
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 140, in __init__
    if max_workers <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

### To Reproduce

Run the following after installing relevant dependencies/libraries/packages etc.:
```python
import aiohttp
import asyncio
async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://python.org') as response:
            print("Status:", response.status)
            print("Content-type:", response.headers['content-type'])
            html = await response.text()
            print("Body:", html[:15], "...")
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

### Expected behavior

Per this site: https://docs.aiohttp.org/en/stable/

I'm expecting to see this: 

```console
Status: 200
Content-type: text/html; charset=utf-8
Body: <!doctype html> ...
```

### Logs/tracebacks

```python-traceback
above
```

### Python Version

```console
$ python --version
The latest buddy!
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: c:\users\jbard\appdata\local\programs\python\python39\lib\site-packages
Requires: async-timeout, attrs, chardet, multidict, typing-extensions, yarl
Required-by: discord.py
```

### multidict Version

```console
$ python -m pip show multidict

Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\jbard\appdata\local\programs\python\python39\lib\site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\jbard\appdata\local\programs\python\python39\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Windows

### Related component

Server, Client

### Additional context

pycharm, not sure about the proxy tbh sorry

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment] 2022-08-20 13:00
Looks like something is broken with your Python install.

Check the contents of that thread.py file. Because the source code in cpython explicitly checks for `None`: https://github.com/python/cpython/blob/3.9/Lib/concurrent/futures/thread.py#L134
And it appears to have been doing that for more than 8 years, so I don't see how you can possible get to that line with a `None` value, unless your Python install is warped..

**Comment by webknjaz** [comment] 2022-08-22 01:36
> unless your Python install is warped..

They could have something in the env monkeypatching stdlib. But other than that, you're probably right and their Python install is broken...

**Comment by webknjaz** [comment] 2022-08-22 01:39
> something in the env monkeypatching stdlib

I suppose this could be caused by something careless like `import builtins; builtins.min = lambda *_, **__: None`.

**Comment by webknjaz** [comment] 2022-08-22 01:40
Since there's no reproducer demonstrating a problem that could originate in aiohttp, there's no action items here. Closing.

**Closed as not planned by webknjaz** 2022-08-22 01:40 UTC
Labels: invalid

**Comment by 007-JB** [comment] 2023-01-19 23:46
cool thanks I reinstalled and better/ best wishes!
