### ISSUE TITLE
Make a protocol ValueError subclass ClientError

### ISSUE THREAD

**Issue by rgeronimi** [fafhrd91/aiohttp#8061] opened 2024-01-26 13:24 UTC
### Is your feature request related to a problem?

When using the aiohttp client, any redirection to a non-HTTP(S) URI will raise, instead of a ClientError, a ValueError:
https://github.com/aio-libs/aiohttp/blob/a379e6344432d5c033f78c2733fe69659e3cff50/aiohttp/client.py#L624

It seems to be the only error in that situation in the aiohttp client codebase. All errors raised while performing a client HTTP call, even OS errors, are wrapped into a class inheriting from ClientError (with multiple inheritance):
https://github.com/aio-libs/aiohttp/blob/a379e6344432d5c033f78c2733fe69659e3cff50/aiohttp/client_exceptions.py#L122

This wrapping is very convenient for users of the aiohttp library, as a single try...except ClientError can catch any client HTTP issue.

However, this specific redirection protocol error escapes this general rule as it does not inherit ClientError. We discovered it while scanning logs of a crawler with millions of URLs.

### Describe the solution you'd like

Have a RedirectionProtocolClientError which inherits from ClientError and, if the library mainteners think this is useful, ValueError.

### Describe alternatives you've considered

Catching myself the various types of errors with specific try....except XXXError clauses. This is very cumbersome to do as it it not documented and it requires scanning a lot of web pages (in our case, millions) to discover these edge cases and make our code more robust, case by case.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment] 2024-01-26 17:25
Seems reasonable.

**Comment by webknjaz** [comment] 2024-01-31 01:46
Duplicate of #2507

**Closed as not planned by webknjaz** 2024-01-31 01:46 UTC
Labels: enhancement
