### ISSUE TITLE
Using eager task factory with aiohttp 3.10.0 and cpython 3.12+ raise an AssertionError in stdlib `asyncio.staggered` (fixed in aiohappyeyeballs 2.4.3+)

### ISSUE THREAD

**Issue by 2-5** [fafhrd91/aiohttp#8599] opened 2024-08-03 16:03 UTC
### Describe the bug

discord.py 2.4.0 throws exception after upgrading aiohttp to 3.10.0:

### To Reproduce

1. use discord.py 2.4.0

### Expected behavior

no exception

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File ".venv/lib/python3.12/site-packages/discord/client.py", line 786, in start
    await self.login(token)
  File ".venv/lib/python3.12/site-packages/discord/client.py", line 620, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/discord/http.py", line 816, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/discord/http.py", line 638, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File ".venv/lib/python3.12/site-packages/aiohttp/client.py", line 1344, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/client.py", line 648, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/connector.py", line 546, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/connector.py", line 954, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1282, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1036, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 89, in start_connection
    sock, _, _ = await staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/staggered.py", line 144, in staggered_race
    raise d.exception()
  File "/usr/lib/python3.12/asyncio/staggered.py", line 101, in run_one_coro
    assert len(running_tasks) == this_index + 2
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Python Version

```console
$ python --version
Python 3.12.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name:                  aiohttp                                                                            
Latest version:        3.10.0                                                                             
Latest stable version: 3.10.0                                                                             
Installed version:     3.10.0                                                                             
Summary:               Async http client/server framework (asyncio)                                       
Requires Python:       >=3.8                                                                              
Author:                                                                                                   
Author email:                                                                                             
License:               Apache 2                                                                           
Homepage:              https://github.com/aio-libs/aiohttp                                                
Project URLs:          Chat: Matrix: https://matrix.to/#/#aio-libs:matrix.org                             
                       Chat: Matrix Space: https://matrix.to/#/#aio-libs-space:matrix.org                 
                       CI: GitHub Actions: https://github.com/aio-libs/aiohttp/actions?query=workflow%3ACI
                       Coverage: codecov: https://codecov.io/github/aio-libs/aiohttp                      
                       Docs: Changelog: https://docs.aiohttp.org/en/stable/changes.html                   
                       Docs: RTD: https://docs.aiohttp.org                                                
                       GitHub: issues: https://github.com/aio-libs/aiohttp/issues                         
                       GitHub: repo: https://github.com/aio-libs/aiohttp                                  
Platform:                                                                                                 
Keywords:
```

### multidict Version

```console
$ python -m pip show multidict
Name:                  multidict                                                      
Latest version:        6.0.5                                                          
Latest stable version: 6.0.5                                                          
Installed version:     6.0.5                                                          
Summary:               multidict implementation                                       
Requires Python:       >=3.7                                                          
Author:                Andrew Svetlov                                                 
Author email:          andrew.svetlov@gmail.com                                       
License:               Apache 2                                                       
Homepage:              https://github.com/aio-libs/multidict                          
Project URLs:          Chat: Gitter: https://gitter.im/aio-libs/Lobby                 
                       CI: GitHub: https://github.com/aio-libs/multidict/actions      
                       Coverage: codecov: https://codecov.io/github/aio-libs/multidict
                       Docs: RTD: https://multidict.aio-libs.org                      
                       GitHub: issues: https://github.com/aio-libs/multidict/issues   
                       GitHub: repo: https://github.com/aio-libs/multidict            
Platform:                                                                             
Keywords:
```

### yarl Version

```console
$ python -m pip show yarl
Name:                  yarl                                                                               
Latest version:        1.9.4                                                                              
Latest stable version: 1.9.4                                                                              
Installed version:     1.9.4                                                                              
Summary:               Yet another URL library                                                            
Requires Python:       >=3.7                                                                              
Author:                Andrew Svetlov                                                                     
Author email:          andrew.svetlov@gmail.com                                                           
License:               Apache-2.0                                                                         
Homepage:              https://github.com/aio-libs/yarl                                                   
Project URLs:          Chat: Matrix: https://matrix.to/#/#aio-libs:matrix.org                             
                       Chat: Matrix Space: https://matrix.to/#/#aio-libs-space:matrix.org                 
                       CI: GitHub Workflows: https://github.com/aio-libs/yarl/actions?query=branch:master 
                       Code of Conduct: https://github.com/aio-libs/.github/blob/master/CODE_OF_CONDUCT.md
                       Coverage: codecov: https://codecov.io/github/aio-libs/yarl                         
                       Docs: Changelog: https://yarl.aio-libs.org/en/latest/changes/                      
                       Docs: RTD: https://yarl.aio-libs.org                                               
                       GitHub: issues: https://github.com/aio-libs/yarl/issues                            
                       GitHub: repo: https://github.com/aio-libs/yarl                                     
Platform:                                                                                                 
Keywords:              cython, cext, yarl
```

### OS

Ubuntu 22.04

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment] 2024-08-03 16:28
This looks like a bug in stdlib asyncio.staggered

Have you had a chance to look through python’s issue tracker?

**Comment by bdraco** [comment] 2024-08-03 16:30
https://github.com/python/cpython/blob/1573d90ce17f27fd30a251de897a35bf598d2655/Lib/asyncio/staggered.py#L90

**Comment by bdraco** [comment] 2024-08-03 16:36
Are you by chance using an eager task factory?

**Comment by 2-5** [comment] 2024-08-03 17:30
Yes, I'm using eager task factory:

```python
loop = asyncio.get_running_loop()
loop.set_task_factory(asyncio.eager_task_factory)
```

aiohttp 3.9.5 worked fine with the same Python 3.12 and the eager task factory, 3.10 is triggering the bug.

**Comment by bdraco** [comment] 2024-08-03 19:33
It looks like asyncio.staggered is broken with eager task factory.  Would you please open a bug report for cpython?

**Comment by bdraco** [comment] 2024-08-03 19:46
A workaround would be to turn off happyeyeballs in the connector.

**Comment by bdraco** [comment] 2024-08-07 12:44
@2-5 I'd like to get this fixed in upstream cpython. Would you please open an issue there?

**Comment by yuvalshi0** [comment] 2024-08-08 07:05
We seem to have a somewhat related issue, only on python 3.11.9 (aiohttp 3.10.1)
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiobotocore/httpsession.py", line 208, in send
response = await self._session.request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 648, in _request
conn = await self._connector.connect(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 546, in connect
proto = await self._create_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 954, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1282, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1036, in _wrap_create_connection
sock = await aiohappyeyeballs.start_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 89, in start_connection
sock, _, _ = await staggered.staggered_race(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/staggered.py", line 144, in staggered_race
raise d.exception()
File "/usr/local/lib/python3.11/asyncio/staggered.py", line 116, in run_one_coro
assert winner_index is None
^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by 2-5** [comment] 2024-08-08 07:42
@bdraco Sorry, I wouldn't know how to report this bug upstream. I don't know what a `staggered_race` is, why what we see here is a Python bug and not an `aiohttp` one, nor what is the expected behavior.

**Comment by gediminasel** [comment] 2024-09-17 21:09
Also getting AssertionError from `assert winner_index is None` but with Python 3.10.12, aiohttp 3.10.3.

**Comment by timborden** [comment] 2024-09-19 10:09
@gediminasel upgrading to Python 3.12.6 appears to have resolved the `assert winner_index is None` AssertionError for us as well....FYI

**Comment by ZeroIntensity** [comment] 2024-09-26 19:58
Upstream issue has been fixed, you guys should be able to get this working whenever the next 3.12 patch is released. In the meantime, you can build 3.12 from source to get the fix.

**Comment by bdraco** [comment] 2024-09-26 21:28
Thank you @ZeroIntensity

**Comment by Dreamsorcerer** [comment] 2024-09-26 21:36
> whenever the next 3.12 patch is released

Tuesday: https://peps.python.org/pep-0693/

There's not action for us to take here, right? We can just close this issue.

**Comment by bdraco** [comment] 2024-09-26 22:03
Actually the fix is a breaking change since the loop argument is removed

**Comment by ZeroIntensity** [comment] 2024-09-26 22:04
It's deprecated, not removed. Why do you need it?

**Comment by bdraco** [comment] 2024-09-26 22:05
@ZeroIntensity https://github.com/python/cpython/commit/2b54a4ebf1ffd2d709570267b3b3bb1dcfec4d53#diff-44556baf5b5e0be424424f6a3058952ceef4bd6a73637f138df33e93def215f7R14 seems to remove it AFAICT

We call it in https://github.com/aio-libs/aiohappyeyeballs/blob/097c9fa75fa6efcb22cf947a90f4db25ef39ebe5/src/aiohappyeyeballs/impl.py#L96

I can ship a new `aiohappyeyeballs` but everyone who has the old version might get a suprise

**Comment by ZeroIntensity** [comment] 2024-09-26 22:09
Oh wait, it looks like the deprecation got taken out without me noticing: https://github.com/python/cpython/commit/3fbbedb0ad64eeba7284d1244158b892497d55c8

I guess this is a breaking change (well, `staggered_race` wasn't documented, so maybe not). If you want to file a new issue asking for `loop` back, go ahead. It's probably easier to just do without it though.

**Comment by bdraco** [comment] 2024-09-26 22:15
https://github.com/python/cpython/issues/124639

**Comment by ZeroIntensity** [comment] 2024-09-26 22:31
It's not supposed to be, yeah.

**Comment by bdraco** [comment] 2024-09-26 22:33
The end goal is to hopefully merge `aiohappyeyeballs` back into cpython so we don't have to worry about that anyways.  

Thanks for the fix.

**Comment by bdraco** [comment] 2024-09-27 14:40
CI runs are hanging with the new code but on 3.13 only

https://github.com/aio-libs/aiohttp/pull/9311
https://github.com/aio-libs/aiohttp/pull/9310

Also staggered_race may not handle KeyboardInterrupt and SystemExit well

https://github.com/aio-libs/aiohappyeyeballs/issues/97

**Comment by bdraco** [comment] 2024-09-28 15:23
It looks like the test failures with the new code and 3.13 are because of a change in the cancellation semantics via https://github.com/python/cpython/pull/117407

**Comment by ZeroIntensity** [comment] 2024-09-28 15:59
Oh boy, that doesn't sound good. This is why it's a bad idea to rely on undocumented APIs. We're working on fixing the backwards compatibility issue via [#124700](https://github.com/python/cpython/pull/124700), but as far as I can see, [#117407](https://github.com/python/cpython/pull/117407) did not make it into 3.12, so you guys might just have to refactor for 3.13.

If you really want, you can file an issue (and PR, core devs are quite busy with 3.13 imminent) for the change in cancellation.

**Comment by bdraco** [comment] 2024-09-28 18:54
Thankfully the problem turned out to be a long standing bug in aiohttp which I just fixed in https://github.com/aio-libs/aiohttp/pull/9326 

It looks like the fix in https://github.com/python/cpython/pull/117407 made it more obvious as the cancellation was leaking out of the context manager because aiohttp's helper was never updated for python 3.11+

**Comment by ZeroIntensity** [comment] 2024-09-28 18:57
Great! Please let us know if you find any other problems ASAP so we can get them fixed before the next 3.12 patch is released on Tuesday.

**Comment by bdraco** [comment] 2024-09-28 18:58
For history the reason we ended up using `asyncio.staggered.staggered_race` was the discussion in this issue https://github.com/aio-libs/aiohttp/issues/4451#issue-539739143

**Comment by bdraco** [comment] 2024-09-28 19:00
> Great! Please let us know if you find any other problems ASAP so we can get them fixed before the next 3.12 patch is released on Tuesday.

The one last loose end is https://github.com/aio-libs/aiohappyeyeballs/issues/97 as it looks like `staggered_race` doesn't handle `SystemExit` or `KeyboardInterrupt` and instead produces `RuntimeError: coroutine ignored GeneratorExit`

AFAICT this is not a regression in the new code and was prevent before the refactor.... [or my test case is bad.](https://github.com/aio-libs/aiohappyeyeballs/blob/04dbbe5be7c38bdbf8ec9e31491fe4d052d15908/tests/test_impl.py#L1373)

**Comment by ZeroIntensity** [comment] 2024-09-28 19:25
I'll take a closer look a little later. I'm guessing it's probably that the mock is bad, rather than a CPython problem -- `SystemExit` seems to be properly raised by `staggered_race` on my end.

**Comment by bdraco** [comment] 2024-09-30 12:17
> Great! Please let us know if you find any other problems ASAP so we can get them fixed before the next 3.12 patch is released on Tuesday.

@ZeroIntensity looks like there is a race in the new code https://github.com/aio-libs/aiohappyeyeballs/issues/100

**Comment by bdraco** [comment] 2024-09-30 18:30
@ZeroIntensity Here is a reproducer test for https://github.com/aio-libs/aiohappyeyeballs/issues/100 

```python

@pytest.mark.asyncio
async def test_multiple_winners():
    """Test multiple winners are handled correctly."""
    loop = asyncio.get_running_loop()
    winners = []
    finish = loop.create_future()

    async def coro(idx):
        await finish
        winners.append(idx)
        return idx

    coros = [partial(coro, idx) for idx in range(4)]

    task = loop.create_task(staggered_race(coros, delay=0.00001))
    await asyncio.sleep(0.1)
    loop.call_soon(finish.set_result, None)
    winner, index, excs = await task
    assert len(winners) == 4
    assert winners == [0, 1, 2, 3]
    assert winner == 0
    assert index == 0
    assert excs == [None, None, None, None]


@pytest.mark.skipif(sys.version_info < (3, 12), reason="requires python3.12 or higher")
def test_multiple_winners_eager_task_factory():
    """Test multiple winners are handled correctly."""
    loop = asyncio.new_event_loop()
    eager_task_factory = asyncio.create_eager_task_factory(asyncio.Task)
    loop.set_task_factory(eager_task_factory)
    asyncio.set_event_loop(None)

    async def run():
        winners = []
        finish = loop.create_future()

        async def coro(idx):
            await finish
            winners.append(idx)
            return idx

        coros = [partial(coro, idx) for idx in range(4)]

        task = loop.create_task(staggered_race(coros, delay=0.00001))
        await asyncio.sleep(0.1)
        loop.call_soon(finish.set_result, None)
        winner, index, excs = await task
        assert len(winners) == 4
        assert winners == [0, 1, 2, 3]
        assert winner == 0
        assert index == 0
        assert excs == [None, None, None, None]

    loop.run_until_complete(run())
```

**Comment by ZeroIntensity** [comment] 2024-09-30 22:22
Sorry, I haven't been able to deal with issues today (which is a bit inconvenient considering the patch is tomorrow). I think the best fix here is rolling back the fix for eager task factories and merging your implementation after you've tested it on PyPI.

**Comment by bdraco** [comment] 2024-09-30 22:37
That sounds like a good plan.  I'll followup again in a few weeks once the new implementation has had a chance to prove out in `aiohappyeyeballs`

**Comment by ZeroIntensity** [comment] 2024-09-30 22:53
Thank you!

**Comment by ZeroIntensity** [comment] 2024-09-30 23:12
FWIW, the revert PR for 3.12.7 is here: https://github.com/python/cpython/pull/124810

This does mean that you won't get support for eager task factories on the prior versions, but that's a tradeoff we have to make here. Hopefully, if your implementation turns out to work properly, we can merge that in to 3.12 and then aiohttp will have things working.

**Comment by bdraco** [comment] 2024-09-30 23:22
Thank you. I'll see if we can yank `aiohappyeyeballs` 2.4.2 (not sure it matters now that 2.4.3 is published, but I don't have the right keys to do that). Hopefully everyone will be able to upgrade to `aiohappyeyeballs` 2.4.3 and the new implementation works out.  

cc @webknjaz

**Comment by ZeroIntensity** [comment] 2024-10-01 15:23
@bdraco could you see if [this PR](https://github.com/python/cpython/pull/124847) works with the aiohttp test suite? We want to be much more cautious when merging things related to `asyncio.staggered` now 🙂

**Comment by bdraco** [comment] 2024-10-01 20:34
I can test it in production later this week.  All my production systems are running the new implementation we shipping in aiohappyeyeballs 2.4.3 and I want to give it a bit more time to bake before switching to testing https://github.com/python/cpython/pull/124847

**Comment by bdraco** [comment] 2024-10-02 12:36
Home Assistant is shipping the new aiohappyeyeballs today.  If all goes well I'll switch over to testing that PR and do some performance comparisons as well

**Comment by ZeroIntensity** [comment] 2024-10-02 13:46
Good to hear!

**Comment by bdraco** [comment] 2024-10-04 14:45
No new issues for aiohappyeyeballs filed, Home Assistant release went well, and my testing went well.  I think I’m ready to start testing above PR today

**Closed as completed** 2024-10-27 20:26 UTC
Labels: bug
