### ISSUE TITLE
aiohttp.ClientSession together with ClusterIp not load balancing

### ISSUE THREAD

**Issue by chunyang-wen** [fafhrd91/aiohttp#6629] opened 2022-02-21 07:39 UTC
### Describe the bug

My Kubernetes PODs are like a(pod_num=1) -> b (pod_num=2). I create a `session = aiohttp.ClientSession` at A to connect service B using CluterIp service address(such as http://b-svc:80). When I try to add 2 pods for B, it seems that the session does not know the two newly added pods and no requests come to the newly two add pods.

`aiohttp` has a `TCPConnector`. By default it has a 10s timeout with the dns cache. I have tried to reduce it or wait for a long time, but I found no access log to the newly added pods.

If I always create a new session to send requests, requests will come to the newly added pods (But it is not suggested by the aiohttp team which involves a connection pool not being used)

What I expect is that

> Requests automatically route [according to certain load balance rules which predefined by k8s] to the newly added pods when I **reuse** the client session.

### To Reproduce

To be more specific, client at A issue requests like this:

```python
import asyncio
import aiohttp
import time

url = "http://b-svc:80/v1/hello"

async def main():
    session = aiohttp.ClientSession()
    for _ in range(100):
        async with session.get(url) as response:
            resp = await response.json()
            print(resp)
        time.sleep(2) # In order to make the cache invalid after 10s

if __name__ == "__main__":
    asyncio.run(main())
```

Server B only returns a json response and it logs every request.

```json
{
    "answer": "world"
}
```

At first, B has only one pod(let's say its pod index = 0) behind the ClusterIp address. When I increase the number of pods behind the ClusterIp address(Let's say, add pods with index = 1, 2, 3), only the first pod(index = 0) created earlier can receive the request [Access log only appear at pod 0, not other 1, 2, 3.]. It seems that the session does not send request to other pods.

### Expected behavior

All the pods behiend the clusterip can receive the requests.

### Logs/tracebacks

```python-traceback
Not available
```

### Python Version

```console
$ python --version
3.7,9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.7.4.post0
```

### multidict Version

```console
$ python -m pip show multidict
5.1.0
```

### yarl Version

```console
$ python -m pip show yarl
1.6.3
```

### OS

Ubuntu

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by chunyang-wen** [comment] 2022-02-21 07:40
Got not enough information on [stackoverflow](https://stackoverflow.com/questions/71155472/aiohttp-clientsession-and-clusterip-not-load-balancing)

**Comment by webknjaz** [comment] 2022-02-21 13:34
If the hostname to IP mapping actually changes, you could do `use_dns_cache=False` per https://docs.aiohttp.org/en/stable/client_advanced.html#tuning-the-dns-cache I suppose. If the routing changes on the IP level but the IP remains the same, then it has nothing to do with aiohttp, look into your lower level networking configuration. This looks like a support question and not a bug, closing.

**Closed as completed by webknjaz** 2022-02-21 13:34 UTC
Labels: invalid, question

**Comment by chunyang-wen** [comment] 2022-02-22 06:41
The root cause is the `keep-alive` mechanism.  Kubernetes cannot handle persistent connections well. Please refer to question[aiohttp.ClientSession and ClusterIp not load balancing](https://stackoverflow.com/questions/71155472/aiohttp-clientsession-and-clusterip-not-load-balancing) and its answers and references.
