### ISSUE TITLE
Threaded resolver threads are live indefinitely

### ISSUE THREAD

**Issue by Rustik665** [fafhrd91/aiohttp#6837] opened 2022-07-21 05:11 UTC
### Describe the bug

When aiohttp uses ThreadedResolver, it creates new thread (uses ThreadPoolExecutor) every time for resolve. After finishing http request, these threads are live forever. Thus, the number of threads is constantly growing and leads to the fact that the system triggers a limit on the number of processes per user who launched the program with aionttp.
Closing connections doesn't help. In other words, these threads will live while your program is running.

### To Reproduce

1. run a simple python program with aiohttp and without installing aiodns
2. make a loop with http requests, closing connection after each request
3. run a htop in another console
4. filter by your program name and you'll see, that every request forks a new thread, that don't die after request finishes, even if we close connection

### Expected behavior

Threads for dns resolving die after request has finished

### Logs/tracebacks

```python-traceback
Here is simple script to reproduce, and output:

import asyncio
import aiohttp
import threading
print(aiohttp.DefaultResolver)


async def count_threads():
    while True:
        await asyncio.sleep(1)
        print(f'threads count: {len(threading.enumerate())}')


async def make_requests():
    for i in range(10):
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10)) as session:
            try:
                async with session.get('https://www.google.ru') as response:
                    await response.text()
            except Exception as ex:
                print(f'exc: {ex}')

    print('requests have finished!')
    for thread in threading.enumerate():
        print(thread)


asyncio.get_event_loop().run_until_complete(asyncio.gather(count_threads(), make_requests()))



Output:

/opt/python3.7/bin/python3.7 /home/local/REGION/rr.fayzullin/PycharmProjects/TEST/test3.py
<class 'aiohttp.resolver.ThreadedResolver'>
threads count: 5
threads count: 9
requests have finished!
<_MainThread(MainThread, started 139807779043136)>
<Thread(ThreadPoolExecutor-0_0, started daemon 139807493482240)>
<Thread(ThreadPoolExecutor-0_1, started daemon 139807478413056)>
<Thread(ThreadPoolExecutor-0_2, started daemon 139807470020352)>
<Thread(ThreadPoolExecutor-0_3, started daemon 139807461627648)>
<Thread(ThreadPoolExecutor-0_4, started daemon 139807453234944)>
<Thread(ThreadPoolExecutor-0_5, started daemon 139807444842240)>
<Thread(ThreadPoolExecutor-0_6, started daemon 139807436449536)>
<Thread(ThreadPoolExecutor-0_7, started daemon 139806956844800)>
<Thread(ThreadPoolExecutor-0_8, started daemon 139806948452096)>
<Thread(ThreadPoolExecutor-0_9, started daemon 139806940059392)>
threads count: 11
threads count: 11
threads count: 11
threads count: 11
threads count: 11
threads count: 11
Traceback (most recent call last):
  File "/home/local/REGION/rr.fayzullin/PycharmProjects/TEST/test3.py", line 33, in <module>
    asyncio.get_event_loop().run_until_complete(asyncio.gather(count_threads(), make_requests()))
  File "/opt/python3.7/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/opt/python3.7/lib64/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/opt/python3.7/lib64/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/python3.7/lib64/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

### Python Version

```console
$ python --version
Python 3.7.3
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /home/local/REGION/rr.fayzullin/.local/lib/python3.7/site-packages
Requires: aiosignal, async-timeout, asynctest, attrs, charset-normalizer, frozenlist, multidict, typing-extensions, yarl
Required-by: aioswagger11
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/local/REGION/rr.fayzullin/.local/lib/python3.7/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/local/REGION/rr.fayzullin/.local/lib/python3.7/site-packages
Requires: idna, multidict, typing-extensions
Required-by: aiohttp
```

### OS

CentOS 7 3.10.0-1127.18.2.el7.x86_64

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment] 2022-07-22 21:24
Hmm, running your script on my machine looks like:
```
> python3 test.py
<class 'aiohttp.resolver.ThreadedResolver'>
threads count: 2
requests have finished!
<_MainThread(MainThread, started 139858234242880)>
<Thread(ThreadPoolExecutor-0_0, started daemon 139858180536064)>
threads count: 2
threads count: 2
threads count: 2
```

**Comment by Dreamsorcerer** [comment] 2022-07-22 21:31
I also don't see any direct use of threads or anything in the code: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/resolver.py#L32

I suspect it may just be the implementation of https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.getaddrinfo

In which case, please test on a newer version of Python, to see if the issue is resolved already. I've just tested with 3.8 and 3.9, neither exceeded 2 threads.

**Comment by Rustik665** [comment] 2022-08-02 06:22
Really! This issue occurs specifically with python3.7, but not with newer versions

**Comment by Dreamsorcerer** [comment] 2022-08-02 17:18
Then I suggest it has been fixed in cpython and you'll just have to upgrade to a newer release. Nothing we can do here.

**Closed as completed by Dreamsorcerer** 2022-08-02 17:18 UTC
Labels: bug
